base_url = "https://blog.xixihaha.tech"
title = "sunyuan's Blog"
description = "个人技术博客"
generate_feeds = true
feed_filenames = ["rss.xml"]
build_search_index = true
default_language = "en"
theme = "apollo"

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[search]
# 包含的内容类型
include_title = true
include_description = true
include_content = true
include_path = false
# 内容截断长度
truncate_content_length = 100
# 搜索索引格式 - 使用fuse.js支持中文
index_format = "fuse_javascript"

[extra]
# 主题设置
theme = "auto"  # auto, light, dark
# 菜单配置
menu = [
    { name = "Home", url = "/", weight = 1 },
    { name = "Search", url = "/search", weight = 2 },
    { name = "Tags", url = "/tags", weight = 3 },
    { name = "Categories", url = "/categories", weight = 4 },
    { name = "About", url = "/about", weight = 5 },
]
# 社交链接
socials = [
    { name = "GitHub", url = "https://github.com/yourusername", icon = "github" },
    { name = "RSS", url = "/rss.xml", icon = "rss" },
]
# 启用搜索
search_enabled = true
# 其他配置
show_reading_time = true
show_word_count = true
show_tags = true
show_categories = true
